### ISSUE TITLE
Images: create a proces for a default image if no image is available

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#13]
Noticing that when there is no image, it breaks the design, would be interesting to create a default for when no image is available.

**Comment by webthingee** [comment]
Perhaps this is a problem for the 'sending' service, not the 'client' product?

**Comment by sirkitree** [comment]
Considering that Drupal has the ability to specify a default image, we would want to try and utilize that I think. So

Step 1: log into drupal and set a default image
2. see if that image comes through in the json response currently
3. if so, use it when the field is empty
3a. if not, we should figure out how to get it to serve the default image

**Comment by webthingee** [comment]
Agree, is path of least resistance.

Thoughts.... (again thinking about a 'mobile app')
. con - performance of getting image vs having a client default.
. pro - ability to have different default images in different situations.

**Comment by sirkitree** [comment]
another pro is that this is what the drupal user would expect to happen. If I change the default image in the drupal back-end, I would expect it to show up on the front end.

**Comment by micahgodbolt** [comment]
I updated the recipe view to place the recipe images as backgrounds of the link tag, rather than inline images. This let me set a % padding on the A tags and make a much more consistent layout, with or without pictures.

As for accessibility, I feel that the image is not an essential part of the recipe (compared to the title and description), and removing it from the DOM won't have any negative effect.
