### ISSUE TITLE
Services vs RestWS

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/copelandia#18]
@makangus 

For the ms... project, I saw that you installed Services and discarded RestWS. I'd like to hear more about why, and if it would be a better solution for us here. What is involved?

RestWS has some shortcomings (namely that I can't understand it because it's so abstracted) as it only serves up entities, and it gives uri's to get info on a file rather than just serve the file info with the original payload for a node. And that is just so far. We're going to want to be able to serve even more from Drupal and need to work with a module we can understand. 

Can you give us a better idea of why you chose Services and if it would help us with some of these things a bit better?

**Comment by deviantintegral** [comment]
I remember there being an issue that RestWS didn't have the ability to filter out fields when sending an object to a client. Though now that I think of it, perhaps that's best done with field permissions? That wouldn't help for entity properties unless field permissions works with properties now.

**Comment by sirkitree** [comment]
Here's another that I just came across that looks like it works with Services: http://drupal.org/project/mast

**Comment by eojthebrave** [comment]
FWIW. RestWS seems to be trying to be a true REST implementation whereas services just aims to well ... serve whatever you tell it to at whatever arbitrary URI you've told it to use.

The file resource here is a good example of that. A true REST implementation returns the resource requested and nothing more. Referenced/Related resources are represented as a resource ID and the URI which can be used to perform another request to retrieve that resource. Which in this case can be obnoxious because Drupal uses references like this all over the place.

**Comment by makangus** [comment]
The last project I abandoned RestWS in favor of actually Views Datasource with Views. RestWS exposes everything in the whole system, and for each node it's displaying every single thing in the node object, like whether commenting is opened for the node. It was too much junk for I needed was Title and a Path of all the nodes of one content type.
Another project I used Services. Services is a little more code to write, but I can manipulate the data before it gets out to the JSON. Also I choose which content types or entities to expose instead of exposing everything. 
I feel like it's fine to use RestWS for decoupling, but if there's somebody else consuming the data I don't want to throw them JSON of the whole node object. Some data in a node or entity object might also be a little sensitive to be public (i.e. say we have an author entity and some articles, people can probably play around with the article json and figure out how to get to the author json, which might expose the author a little bit more than we want.)

**Comment by sirkitree** [comment]
Yeah, overall I'm leaning more and more towards Services because of that fact that we need more that RestWS offers, and because we want to tailor responses.

Is their any reason we might not want to use Services?

**Comment by webthingee** [comment]
+1 for services.
I have used it a few times and really like it both on the Drupal admin side, as well as on the Client side.

**Comment by makangus** [comment]
+1 for Services too. Services will also solve problems like #10

**Comment by eojthebrave** [comment]
Also a vote for services as I've used it a tonne and it's got better integration with a lot of other tools we might need down the road like OAuth etc.

It would be interesting to see if there's a way that you can provide a helper for Entity API for exposing a custom entities info to services. Something like how it handles revionsable content or views integration. One benefit of RestWS is it just works out of the box with anything that is an entity. Services requires a lot of hand holding for custom data types. For a future discussion though. :)
