### ISSUE TITLE
User registration and authentication

### ISSUE THREAD

**Issue by juampynr** [Lullabot/copelandia#23]
Provide a way for users to register and then authenticate in the application.

Users will be created in the Drupal database and this db will be queried through a Web Service on authentication.

**Comment by sirkitree** [comment]
This is interesting, and probably not limited to symphony actually. We certainly need a user in Drupal in order to allow them to create/edit content, but if we can make the web service general enough, we might be able to allow clients to use various authentication methods.

For instance, you might want to just implement straight up Drupal user creation in Symphony, but perhaps we want to allow Google Plus sign-ins for the AngularJS client.

This probably also hinges a bit on getting Services in place rather than RestWS per #18

**Comment by micahgodbolt** [comment]
If only there were a good angular plugin for google plus sign-in <.<

**Comment by sirkitree** [comment]
:laughing: 

My point is that the web service should be general enough that we can implement whatever from the client side.

**Comment by juampynr** [comment]
This is possible. In Symfony you can define several User Providers. I need to dive deeper into this:

http://symfony.com/doc/2.0/cookbook/security/custom_provider.html

**Comment by webthingee** [comment]
I have had good luck with this using jquery.

**Comment by juampynr** [comment]
Since the REST+Oauth server was set up at #30, the Drupal part of this should be already done and now it is up to the client sites to use the user endpoint to register users.

I have created https://github.com/Lullabot/copelandia-symfony/issues/3 to track the Symfony part of this.

Closing.
